name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -c Release -o ./dist
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        # Build directory to deploy
        build_dir: dist/wwwroot
        # Write the given domain name to the CNAME file
        fqdn: jwt.developer.li
      env:
        GITHUB_PAT: ${{ secrets.GIT_PAT }}

